### ISSUE TITLE
Feedback and Suggested Fixes

### ISSUE THREAD

**Issue by Welding-Torch** [hackclub/some-assembly-required#47]
Hi! I just read through the entire thing in one sitting. I tried learning assembly a couple of times, but I never actually understood it until I read this. Thank you. The entire guide is written in a friendly manner that made it easy to understand.

I noticed a couple of things:
1. In the 'Conditionals' chapter, on line 33, what is rdi ? In it's place, shouldn't there be rbx?
2. In the 'Loop De Loop' chapter in the function .calculatePower which starts on line 48, there is no mention of rbx which is the base. I don't entirely understand this.
3. In the 'Uppercaser' chapter on line 44 rdi has been described twice. Shouldn't that be rsi in its place?

Hoping this helps.

**Comment by jessicard** [comment]
Ahhh I'm so glad it helped assembly click for you! That's wonderful :) And thanks for noticing these!

1. Nice catch, fixed in https://github.com/hackclub/some-assembly-required/pull/44
2. Totally goofed there! Fixed in https://github.com/hackclub/some-assembly-required/commit/f7b0ef788710e1a9e072b7cc920040d07814906b
3. Yes it should! Fixed in https://github.com/hackclub/some-assembly-required/pull/42/files

Thank you so much! 🙏 🙇
